development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: babycasts_development
  pool: 5
  host: 127.0.0.1
  username: root

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: babycasts_test
  pool: 5
  host: 127.0.0.1
  username: root